spring.application.name=agrosat
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.username=rm560914
spring.datasource.password=fiap25
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

logging.level.root=INFO
logging.level.br.com.empresa.springCrud.AppExample=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.file.name=./logs/application.log

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.core=TRACE
logging.level.org.springframework.transaction=TRACE

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.filter=true

openweather.api-key=${OPENWEATHER_API_KEY}

spring.activemq.broker-url=vm://embedded?broker.persistent=false
spring.activemq.in-memory=true
spring.activemq.packages.trust-all=true